// SPDX-License-Identifier: MIT
// apps/demo — Pre-built Bento layouts for each Generative UI intent.

import type { BentoLayoutConfig } from "@novasphere/ui-bento";
import { INTENT, type Intent } from "./intents";

const DEFAULT: BentoLayoutConfig = [
  {
    id: "revenue",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 0,
    title: "Revenue",
  },
  {
    id: "users",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 1,
    title: "Users",
  },
  {
    id: "ai-calls",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 2,
    title: "AI Calls",
  },
  {
    id: "churn",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 3,
    title: "Churn",
  },
  {
    id: "activity",
    colSpan: 4,
    rowSpan: 2,
    moduleId: "ActivityFeed",
    visible: true,
    order: 4,
    title: "Activity",
  },
  {
    id: "area-chart",
    colSpan: 8,
    rowSpan: 1,
    moduleId: "AreaChartModule",
    visible: true,
    order: 5,
    title: "Traffic & Revenue",
  },
  {
    id: "donut",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "DonutChartModule",
    visible: true,
    order: 6,
    title: "Breakdown",
  },
  {
    id: "heatmap",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "HeatmapModule",
    visible: true,
    order: 7,
    title: "Usage Heatmap",
  },
  {
    id: "quota",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "QuotaModule",
    visible: false,
    order: 8,
    title: "Quota",
  },
  {
    id: "globe",
    colSpan: 4,
    rowSpan: 2,
    moduleId: "GlobeModule",
    visible: false,
    order: 9,
    title: "Global Distribution",
  },
  {
    id: "anomaly-banner",
    colSpan: 12,
    rowSpan: 1,
    moduleId: "AnomalyBanner",
    visible: false,
    order: 10,
    title: "Anomaly Detected",
  },
  {
    id: "agent-insight",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "AgentInsightCard",
    visible: false,
    order: 11,
    title: "Agent Insight",
  },
];

// CEO_VIEW:
//   - Revenue hero (6x2)
//   - Users (6x1)
//   - Area chart full-width (12x1)
//   - Donut (6x1)
//   - Agent insight (6x1)
//   - Hidden: heatmap, ai-calls, churn, activity
const CEO_VIEW: BentoLayoutConfig = [
  {
    id: "revenue",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "MetricCard",
    visible: true,
    order: 0,
    title: "Revenue",
  },
  {
    id: "users",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 1,
    title: "Users",
  },
  {
    id: "area-chart",
    colSpan: 12,
    rowSpan: 1,
    moduleId: "AreaChartModule",
    visible: true,
    order: 2,
    title: "Traffic & Revenue",
  },
  {
    id: "donut",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "DonutChartModule",
    visible: true,
    order: 3,
    title: "Revenue Breakdown",
  },
  {
    id: "agent-insight",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "AgentInsightCard",
    visible: true,
    order: 4,
    title: "Executive Summary",
  },
  {
    id: "heatmap",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "HeatmapModule",
    visible: false,
    order: 5,
    title: "Usage Heatmap",
  },
  {
    id: "ai-calls",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: false,
    order: 6,
    title: "AI Calls",
  },
  {
    id: "churn",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: false,
    order: 7,
    title: "Churn",
  },
  {
    id: "activity",
    colSpan: 4,
    rowSpan: 2,
    moduleId: "ActivityFeed",
    visible: false,
    order: 8,
    title: "Activity",
  },
  {
    id: "quota",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "QuotaModule",
    visible: false,
    order: 9,
    title: "Quota",
  },
  {
    id: "globe",
    colSpan: 4,
    rowSpan: 2,
    moduleId: "GlobeModule",
    visible: false,
    order: 10,
    title: "Global Distribution",
  },
  {
    id: "anomaly-banner",
    colSpan: 12,
    rowSpan: 1,
    moduleId: "AnomalyBanner",
    visible: false,
    order: 11,
    title: "Anomaly Detected",
  },
];

// ENGINEER_VIEW:
//   - AI calls (4x1)
//   - Heatmap (8x1)
//   - Quota (6x2)
//   - Area chart (6x1)
//   - Activity (6x2)
//   - Hidden: donut, revenue, users
const ENGINEER_VIEW: BentoLayoutConfig = [
  {
    id: "ai-calls",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 0,
    title: "AI Calls",
  },
  {
    id: "heatmap",
    colSpan: 8,
    rowSpan: 1,
    moduleId: "HeatmapModule",
    visible: true,
    order: 1,
    title: "Usage Heatmap",
  },
  {
    id: "quota",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "QuotaModule",
    visible: true,
    order: 2,
    title: "Quota & Limits",
  },
  {
    id: "area-chart",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "AreaChartModule",
    visible: true,
    order: 3,
    title: "Traffic & Latency",
  },
  {
    id: "activity",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "ActivityFeed",
    visible: true,
    order: 4,
    title: "Infrastructure Events",
  },
  {
    id: "donut",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "DonutChartModule",
    visible: false,
    order: 5,
    title: "Breakdown",
  },
  {
    id: "revenue",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: false,
    order: 6,
    title: "Revenue",
  },
  {
    id: "users",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: false,
    order: 7,
    title: "Users",
  },
  {
    id: "churn",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 8,
    title: "Churn",
  },
  {
    id: "globe",
    colSpan: 4,
    rowSpan: 2,
    moduleId: "GlobeModule",
    visible: false,
    order: 9,
    title: "Global Distribution",
  },
  {
    id: "anomaly-banner",
    colSpan: 12,
    rowSpan: 1,
    moduleId: "AnomalyBanner",
    visible: false,
    order: 10,
    title: "Anomaly Detected",
  },
  {
    id: "agent-insight",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "AgentInsightCard",
    visible: false,
    order: 11,
    title: "Agent Insight",
  },
];

// MORNING_BRIEFING:
//   - AgentInsightCard full-width at top
//   - Revenue, Users, AI Calls (4x1 each)
//   - Activity (6x2)
//   - Area chart (6x1)
//   - Hidden: heatmap, donut, churn
const MORNING_BRIEFING: BentoLayoutConfig = [
  {
    id: "agent-insight",
    colSpan: 12,
    rowSpan: 1,
    moduleId: "AgentInsightCard",
    visible: true,
    order: 0,
    title: "Morning Briefing",
  },
  {
    id: "revenue",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 1,
    title: "Revenue",
  },
  {
    id: "users",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 2,
    title: "Users",
  },
  {
    id: "ai-calls",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 3,
    title: "AI Calls",
  },
  {
    id: "activity",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "ActivityFeed",
    visible: true,
    order: 4,
    title: "Overnight Activity",
  },
  {
    id: "area-chart",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "AreaChartModule",
    visible: true,
    order: 5,
    title: "Today’s Trend",
  },
  {
    id: "heatmap",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "HeatmapModule",
    visible: false,
    order: 6,
    title: "Usage Heatmap",
  },
  {
    id: "donut",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "DonutChartModule",
    visible: false,
    order: 7,
    title: "Breakdown",
  },
  {
    id: "churn",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: false,
    order: 8,
    title: "Churn",
  },
  {
    id: "quota",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "QuotaModule",
    visible: false,
    order: 9,
    title: "Quota",
  },
  {
    id: "globe",
    colSpan: 4,
    rowSpan: 2,
    moduleId: "GlobeModule",
    visible: false,
    order: 10,
    title: "Global Distribution",
  },
  {
    id: "anomaly-banner",
    colSpan: 12,
    rowSpan: 1,
    moduleId: "AnomalyBanner",
    visible: false,
    order: 11,
    title: "Anomaly Detected",
  },
];

// EOD_SUMMARY:
//   - Area chart full-width 12x2
//   - Revenue, Users, AI Calls, Churn (3x1 each)
//   - AgentInsightCard (6x1)
//   - Activity (6x2)
//   - Hidden: heatmap, donut, quota
const EOD_SUMMARY: BentoLayoutConfig = [
  {
    id: "area-chart",
    colSpan: 12,
    rowSpan: 2,
    moduleId: "AreaChartModule",
    visible: true,
    order: 0,
    title: "Day Trend",
  },
  {
    id: "revenue",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 1,
    title: "Revenue",
  },
  {
    id: "users",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 2,
    title: "Users",
  },
  {
    id: "ai-calls",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 3,
    title: "AI Calls",
  },
  {
    id: "churn",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 4,
    title: "Churn",
  },
  {
    id: "agent-insight",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "AgentInsightCard",
    visible: true,
    order: 5,
    title: "EOD Summary",
  },
  {
    id: "activity",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "ActivityFeed",
    visible: true,
    order: 6,
    title: "Today’s Activity",
  },
  {
    id: "heatmap",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "HeatmapModule",
    visible: false,
    order: 7,
    title: "Usage Heatmap",
  },
  {
    id: "donut",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "DonutChartModule",
    visible: false,
    order: 8,
    title: "Breakdown",
  },
  {
    id: "quota",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "QuotaModule",
    visible: false,
    order: 9,
    title: "Quota",
  },
  {
    id: "globe",
    colSpan: 4,
    rowSpan: 2,
    moduleId: "GlobeModule",
    visible: false,
    order: 10,
    title: "Global Distribution",
  },
  {
    id: "anomaly-banner",
    colSpan: 12,
    rowSpan: 1,
    moduleId: "AnomalyBanner",
    visible: false,
    order: 11,
    title: "Anomaly Detected",
  },
];

// FOCUS_REVENUE:
//   - Revenue (6x2)
//   - Area chart (6x2)
//   - Agent insight (4x1)
//   - Donut (4x1)
//   - Users (4x1)
//   - Hidden: heatmap, ai-calls, churn, activity, quota
const FOCUS_REVENUE: BentoLayoutConfig = [
  {
    id: "revenue",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "MetricCard",
    visible: true,
    order: 0,
    title: "Revenue",
  },
  {
    id: "area-chart",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "AreaChartModule",
    visible: true,
    order: 1,
    title: "Revenue Trend",
  },
  {
    id: "agent-insight",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "AgentInsightCard",
    visible: true,
    order: 2,
    title: "Revenue Insights",
  },
  {
    id: "donut",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "DonutChartModule",
    visible: true,
    order: 3,
    title: "Revenue Breakdown",
  },
  {
    id: "users",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 4,
    title: "Users",
  },
  {
    id: "heatmap",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "HeatmapModule",
    visible: false,
    order: 5,
    title: "Usage Heatmap",
  },
  {
    id: "ai-calls",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: false,
    order: 6,
    title: "AI Calls",
  },
  {
    id: "churn",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: false,
    order: 7,
    title: "Churn",
  },
  {
    id: "activity",
    colSpan: 4,
    rowSpan: 2,
    moduleId: "ActivityFeed",
    visible: false,
    order: 8,
    title: "Activity",
  },
  {
    id: "quota",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "QuotaModule",
    visible: false,
    order: 9,
    title: "Quota",
  },
  {
    id: "globe",
    colSpan: 4,
    rowSpan: 2,
    moduleId: "GlobeModule",
    visible: false,
    order: 10,
    title: "Global Distribution",
  },
  {
    id: "anomaly-banner",
    colSpan: 12,
    rowSpan: 1,
    moduleId: "AnomalyBanner",
    visible: false,
    order: 11,
    title: "Anomaly Detected",
  },
];

// FOCUS_USERS:
//   - Users (6x2)
//   - Churn (6x1)
//   - Donut (6x1)
//   - Activity (6x2)
//   - Area chart (12x1)
//   - Hidden: heatmap, ai-calls, quota, revenue
const FOCUS_USERS: BentoLayoutConfig = [
  {
    id: "users",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "MetricCard",
    visible: true,
    order: 0,
    title: "Users",
  },
  {
    id: "churn",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 1,
    title: "Churn",
  },
  {
    id: "donut",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "DonutChartModule",
    visible: true,
    order: 2,
    title: "User Segments",
  },
  {
    id: "activity",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "ActivityFeed",
    visible: true,
    order: 3,
    title: "User Activity",
  },
  {
    id: "area-chart",
    colSpan: 12,
    rowSpan: 1,
    moduleId: "AreaChartModule",
    visible: true,
    order: 4,
    title: "User Growth",
  },
  {
    id: "heatmap",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "HeatmapModule",
    visible: false,
    order: 5,
    title: "Usage Heatmap",
  },
  {
    id: "ai-calls",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: false,
    order: 6,
    title: "AI Calls",
  },
  {
    id: "quota",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "QuotaModule",
    visible: false,
    order: 7,
    title: "Quota",
  },
  {
    id: "revenue",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: false,
    order: 8,
    title: "Revenue",
  },
  {
    id: "globe",
    colSpan: 4,
    rowSpan: 2,
    moduleId: "GlobeModule",
    visible: false,
    order: 9,
    title: "Global Distribution",
  },
  {
    id: "anomaly-banner",
    colSpan: 12,
    rowSpan: 1,
    moduleId: "AnomalyBanner",
    visible: false,
    order: 10,
    title: "Anomaly Detected",
  },
  {
    id: "agent-insight",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "AgentInsightCard",
    visible: false,
    order: 11,
    title: "Agent Insight",
  },
];

// FOCUS_ENGINEERING:
//   - AI calls (6x2)
//   - Heatmap (6x2)
//   - Quota (4x1)
//   - Area chart (8x1)
//   - Activity (12x2)
//   - Hidden: revenue, users, churn, donut
const FOCUS_ENGINEERING: BentoLayoutConfig = [
  {
    id: "ai-calls",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "MetricCard",
    visible: true,
    order: 0,
    title: "AI Calls",
  },
  {
    id: "heatmap",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "HeatmapModule",
    visible: true,
    order: 1,
    title: "Usage Heatmap",
  },
  {
    id: "quota",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "QuotaModule",
    visible: true,
    order: 2,
    title: "Quota & Limits",
  },
  {
    id: "area-chart",
    colSpan: 8,
    rowSpan: 1,
    moduleId: "AreaChartModule",
    visible: true,
    order: 3,
    title: "Traffic & Latency",
  },
  {
    id: "activity",
    colSpan: 12,
    rowSpan: 2,
    moduleId: "ActivityFeed",
    visible: true,
    order: 4,
    title: "Infrastructure Events",
  },
  {
    id: "revenue",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: false,
    order: 5,
    title: "Revenue",
  },
  {
    id: "users",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: false,
    order: 6,
    title: "Users",
  },
  {
    id: "churn",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: false,
    order: 7,
    title: "Churn",
  },
  {
    id: "donut",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "DonutChartModule",
    visible: false,
    order: 8,
    title: "Breakdown",
  },
  {
    id: "globe",
    colSpan: 4,
    rowSpan: 2,
    moduleId: "GlobeModule",
    visible: false,
    order: 9,
    title: "Global Distribution",
  },
  {
    id: "anomaly-banner",
    colSpan: 12,
    rowSpan: 1,
    moduleId: "AnomalyBanner",
    visible: false,
    order: 10,
    title: "Anomaly Detected",
  },
  {
    id: "agent-insight",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "AgentInsightCard",
    visible: false,
    order: 11,
    title: "Agent Insight",
  },
];

// ANOMALY_REVENUE:
//   - AnomalyBanner (12x1)
//   - Revenue (6x2)
//   - Area chart (6x2)
//   - Agent insight (6x1)
//   - Donut (6x1)
//   - Hidden: heatmap, quota, activity
const ANOMALY_REVENUE: BentoLayoutConfig = [
  {
    id: "anomaly-banner",
    colSpan: 12,
    rowSpan: 1,
    moduleId: "AnomalyBanner",
    visible: true,
    order: 0,
    title: "Revenue Anomaly",
  },
  {
    id: "revenue",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "MetricCard",
    visible: true,
    order: 1,
    title: "Revenue",
  },
  {
    id: "area-chart",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "AreaChartModule",
    visible: true,
    order: 2,
    title: "Revenue Trend",
  },
  {
    id: "agent-insight",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "AgentInsightCard",
    visible: true,
    order: 3,
    title: "Anomaly Analysis",
  },
  {
    id: "donut",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "DonutChartModule",
    visible: true,
    order: 4,
    title: "Segment Breakdown",
  },
  {
    id: "heatmap",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "HeatmapModule",
    visible: false,
    order: 5,
    title: "Usage Heatmap",
  },
  {
    id: "quota",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "QuotaModule",
    visible: false,
    order: 6,
    title: "Quota",
  },
  {
    id: "activity",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "ActivityFeed",
    visible: false,
    order: 7,
    title: "Activity",
  },
  {
    id: "users",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 8,
    title: "Users",
  },
  {
    id: "ai-calls",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 9,
    title: "AI Calls",
  },
  {
    id: "globe",
    colSpan: 4,
    rowSpan: 2,
    moduleId: "GlobeModule",
    visible: false,
    order: 10,
    title: "Global Distribution",
  },
  {
    id: "churn",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 11,
    title: "Churn",
  },
];

// ANOMALY_INFRA:
//   - AnomalyBanner (12x1)
//   - AI calls (6x2)
//   - Heatmap (6x2)
//   - Quota (6x1)
//   - Activity (6x2)
//   - Hidden: revenue, users, churn, donut
const ANOMALY_INFRA: BentoLayoutConfig = [
  {
    id: "anomaly-banner",
    colSpan: 12,
    rowSpan: 1,
    moduleId: "AnomalyBanner",
    visible: true,
    order: 0,
    title: "Infrastructure Anomaly",
  },
  {
    id: "ai-calls",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "MetricCard",
    visible: true,
    order: 1,
    title: "AI Calls",
  },
  {
    id: "heatmap",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "HeatmapModule",
    visible: true,
    order: 2,
    title: "Usage Heatmap",
  },
  {
    id: "quota",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "QuotaModule",
    visible: true,
    order: 3,
    title: "Quota & Limits",
  },
  {
    id: "activity",
    colSpan: 6,
    rowSpan: 2,
    moduleId: "ActivityFeed",
    visible: true,
    order: 4,
    title: "Infrastructure Events",
  },
  {
    id: "revenue",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: false,
    order: 5,
    title: "Revenue",
  },
  {
    id: "users",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: false,
    order: 6,
    title: "Users",
  },
  {
    id: "churn",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: false,
    order: 7,
    title: "Churn",
  },
  {
    id: "donut",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "DonutChartModule",
    visible: false,
    order: 8,
    title: "Breakdown",
  },
  {
    id: "globe",
    colSpan: 4,
    rowSpan: 2,
    moduleId: "GlobeModule",
    visible: false,
    order: 9,
    title: "Global Distribution",
  },
  {
    id: "agent-insight",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "AgentInsightCard",
    visible: false,
    order: 10,
    title: "Agent Insight",
  },
];

// EXPAND_CHART:
//   - Area chart (12x3)
//   - Revenue, Users, AI Calls, Churn (3x1 each)
//   - Hidden: heatmap, donut, activity, quota, agent-insight
const EXPAND_CHART: BentoLayoutConfig = [
  {
    id: "area-chart",
    colSpan: 12,
    rowSpan: 3,
    moduleId: "AreaChartModule",
    visible: true,
    order: 0,
    title: "Expanded Trend",
  },
  {
    id: "revenue",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 1,
    title: "Revenue",
  },
  {
    id: "users",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 2,
    title: "Users",
  },
  {
    id: "ai-calls",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 3,
    title: "AI Calls",
  },
  {
    id: "churn",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 4,
    title: "Churn",
  },
  {
    id: "heatmap",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "HeatmapModule",
    visible: false,
    order: 5,
    title: "Usage Heatmap",
  },
  {
    id: "donut",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "DonutChartModule",
    visible: false,
    order: 6,
    title: "Breakdown",
  },
  {
    id: "activity",
    colSpan: 4,
    rowSpan: 2,
    moduleId: "ActivityFeed",
    visible: false,
    order: 7,
    title: "Activity",
  },
  {
    id: "quota",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "QuotaModule",
    visible: false,
    order: 8,
    title: "Quota",
  },
  {
    id: "agent-insight",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "AgentInsightCard",
    visible: false,
    order: 9,
    title: "Agent Insight",
  },
  {
    id: "globe",
    colSpan: 4,
    rowSpan: 2,
    moduleId: "GlobeModule",
    visible: false,
    order: 10,
    title: "Global Distribution",
  },
  {
    id: "anomaly-banner",
    colSpan: 12,
    rowSpan: 1,
    moduleId: "AnomalyBanner",
    visible: false,
    order: 11,
    title: "Anomaly Detected",
  },
];

// EXPAND_ACTIVITY:
//   - Activity (12x3)
//   - Revenue, Users, AI Calls, Churn (3x1 each)
//   - Hidden: heatmap, donut, area-chart, quota, agent-insight
const EXPAND_ACTIVITY: BentoLayoutConfig = [
  {
    id: "activity",
    colSpan: 12,
    rowSpan: 3,
    moduleId: "ActivityFeed",
    visible: true,
    order: 0,
    title: "Expanded Activity",
  },
  {
    id: "revenue",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 1,
    title: "Revenue",
  },
  {
    id: "users",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 2,
    title: "Users",
  },
  {
    id: "ai-calls",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 3,
    title: "AI Calls",
  },
  {
    id: "churn",
    colSpan: 3,
    rowSpan: 1,
    moduleId: "MetricCard",
    visible: true,
    order: 4,
    title: "Churn",
  },
  {
    id: "heatmap",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "HeatmapModule",
    visible: false,
    order: 5,
    title: "Usage Heatmap",
  },
  {
    id: "donut",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "DonutChartModule",
    visible: false,
    order: 6,
    title: "Breakdown",
  },
  {
    id: "area-chart",
    colSpan: 8,
    rowSpan: 1,
    moduleId: "AreaChartModule",
    visible: false,
    order: 7,
    title: "Trend",
  },
  {
    id: "quota",
    colSpan: 4,
    rowSpan: 1,
    moduleId: "QuotaModule",
    visible: false,
    order: 8,
    title: "Quota",
  },
  {
    id: "agent-insight",
    colSpan: 6,
    rowSpan: 1,
    moduleId: "AgentInsightCard",
    visible: false,
    order: 9,
    title: "Agent Insight",
  },
  {
    id: "globe",
    colSpan: 4,
    rowSpan: 2,
    moduleId: "GlobeModule",
    visible: false,
    order: 10,
    title: "Global Distribution",
  },
  {
    id: "anomaly-banner",
    colSpan: 12,
    rowSpan: 1,
    moduleId: "AnomalyBanner",
    visible: false,
    order: 11,
    title: "Anomaly Detected",
  },
];

export const LAYOUT_PRESETS: Record<Intent, BentoLayoutConfig> = {
  [INTENT.DEFAULT_LAYOUT]: DEFAULT,
  [INTENT.CEO_VIEW]: CEO_VIEW,
  [INTENT.ENGINEER_VIEW]: ENGINEER_VIEW,
  [INTENT.MORNING_BRIEFING]: MORNING_BRIEFING,
  [INTENT.EOD_SUMMARY]: EOD_SUMMARY,
  [INTENT.FOCUS_REVENUE]: FOCUS_REVENUE,
  [INTENT.FOCUS_USERS]: FOCUS_USERS,
  [INTENT.FOCUS_ENGINEERING]: FOCUS_ENGINEERING,
  [INTENT.ANOMALY_REVENUE]: ANOMALY_REVENUE,
  [INTENT.ANOMALY_INFRA]: ANOMALY_INFRA,
  [INTENT.EXPAND_CHART]: EXPAND_CHART,
  [INTENT.EXPAND_ACTIVITY]: EXPAND_ACTIVITY,
  // Conversational intents do not change layout; we map to DEFAULT as a safe fallback.
  [INTENT.CONVERSATIONAL]: DEFAULT,
};

export function getLayout(intent: Intent): BentoLayoutConfig {
  return LAYOUT_PRESETS[intent] ?? LAYOUT_PRESETS[INTENT.DEFAULT_LAYOUT];
}

